spring.application.name=vehicle-service-ms

server.port=8081

# =========================
# LOCAL
# =========================

# spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle_rental_db
# eureka.client.service-url.defaultZone=http://localhost:8761/eureka
# eureka.instance.hostname=localhost

# =========================
# DOCKER
# =========================

spring.datasource.url=jdbc:postgresql://postgres:5432/vehicle_rental_db
spring.datasource.username=postgres
spring.datasource.password=miguel
spring.datasource.driver-class-name=org.postgresql.Driver

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

eureka.instance.prefer-ip-address=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true