spring.application.name=gateway-service

server.port=8080

# =========================
# LOCAL
# =========================

# eureka.client.service-url.defaultZone=http://localhost:8761/eureka
# eureka.instance.hostname=localhost

# =========================
# DOCKER
# =========================

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

eureka.instance.prefer-ip-address=true

# =========================
# ROUTES
# =========================

spring.cloud.gateway.routes[0].id=vehicle-service
spring.cloud.gateway.routes[0].uri=lb://VEHICLE-SERVICE-MS
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/vehicles/**

spring.cloud.gateway.routes[1].id=operation-service
spring.cloud.gateway.routes[1].uri=lb://OPERATION-SERVICE-MS
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/operations/**